import path from 'path';
import fs from 'fs';
import readline from 'readline';
import { fileURLToPath } from 'url';
import { getSpecificProduct } from './database.js';
import { LlamaModel, LlamaContext, LlamaChatSession } from 'node-llama-cpp';

// Initialize the Llama Model
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const modelPath = path.join(__dirname, "models", "llama-2-7b-chat.Q3_K_S.gguf");
// const model = new LlamaModel({ modelPath });
const model = new LlamaModel({
  modelPath,
  gpuLayers: 33,
  streaming: true
});

const context = new LlamaContext({ model });
const session = new LlamaChatSession({ context });

console.log("llama_adding_knowledge_to_model");

// Prompt generated by ChatGPT
async function addKnowledgeToModel(){
  const knowledge = fs.readFileSync('starting_context.txt', 'utf-8');
  const lines = knowledge.split(/\r?\n/);

  for (const line of lines) {
    await session.prompt(line);
  }
  console.log("llama_knowledge_added_to_model");
}

addKnowledgeToModel();







export async function handleRequest(res, userPrompt){
  
  try {
    if (!userPrompt) {
      console.log("No user prompt provided")
      return new Error('No user prompt provided');
    }

    const productCategories = ["phones", "tvs", "headphones", "laptops", "watches"];
    let userPromptCategory, userPromptFilter, direction;

    for (const category of productCategories) {
      if (userPrompt.includes(category) || userPrompt.includes(category.slice(0, -1))) {
        userPromptCategory = category;
        break;
      }
    }

    if(userPrompt.includes("cheap") || userPrompt.includes("economic") || userPrompt.includes("cost") || userPrompt.includes("price") || userPrompt.includes("reasonable") || userPrompt.includes("economical")){
      userPromptFilter = "price";
      direction = "ASC";
    } else if (userPrompt.includes("expensive") || userPrompt.includes("luxury") || userPrompt.includes("premium") || userPrompt.includes("high-end") || userPrompt.includes("costly") || userPrompt.includes("pricey")){
      userPromptFilter = "price";
      direction = "DESC";
    } else if (userPrompt.includes("best") || userPrompt.includes("top") || userPrompt.includes("highest") || userPrompt.includes("greatest") || userPrompt.includes("most")){
      userPromptFilter = "rating";
      direction = "DESC";
    } else if (userPrompt.includes("worst") || userPrompt.includes("bottom") || userPrompt.includes("lowest") || userPrompt.includes("least")){
      userPromptFilter = "rating";
      direction = "ASC";
    }

    if(userPromptCategory && userPromptFilter && direction){
      const products = await getSpecificProduct(userPromptCategory, userPromptFilter, direction, 3);
      const reply = session.prompt("suggested products: " + JSON.stringify(products) + " user prompt: " + userPrompt, {
        maxTokens: 70,
      });
      return reply;
    } else if(userPromptCategory){
      const products = await getSpecificProduct(userPromptCategory, "price", "ASC", 3);
      const reply = session.prompt("suggested products: " + JSON.stringify(products) + " user prompt: " + userPrompt, {
        maxTokens: 70,
      });
      console.log("suggested products: " + JSON.stringify(products) + " user prompt: " + userPrompt)
      return reply;
    } else {
      const reply = session.prompt(userPrompt, {
        maxTokens: 70,
      });
      return reply;
    }
  } catch (error) {
    console.error(error);
  }
}